spring:
  profiles:
    active:
    - dev

  http:
    multipart:
      maxFileSize: 100MB
      maxRequestSize: 100MB
    jmx:
      default-domain: mall-admin

  server:
    context-path: /mall-admin

