logging:
  config: classpath:log4j2-spring-dev.yml

server:
  port: 9010

# 数据库访问配置
spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: Founder123
    port: 6379
    timeout: 3000 #连接超时时间 单位ms
    #redis线程池设置
    jedis:
      pool:
        max-idle: 500
        min-idle: 50

  dubbo:
    application:
      name: mall-admin
    consumer:
      check: false #关闭所有服务的启动时检查 (没有提供者时报错)
      timeout: 10000
    registry:
      protocol: zookeeper
      address: 127.0.0.1:2181


shiro:
  loginUrl: /toLogin
  ## session管理方式，true使用shiro提供的session管理，false则使用servlet提供的session管理
  userNativeSessionManager: true
  sessionManager:
    sessionIdUrlRewritingEnabled: false






