spring:
  profiles:
    active:
    - dev

server:
  context-path: /ic-service
  
mybatis:
  mapper-locations:
  - classpath*:mybatis/*.xml

pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
